entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: gh-checkout
      port: exec
  - src:
      node: run-v1-peach-dolphin-pineapple
      port: exec-success
    dst:
      node: run-v1-orange-panda-gray
      port: exec
  - src:
      node: run-v1-orange-panda-gray
      port: exec-success
    dst:
      node: gh-codecov-codecov-action-v4-5-0-pomegranate-blueberry-red
      port: exec
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: gh-actions-setup-python-v5-2-0-lion-blue-plum
      port: exec
  - src:
      node: gh-actions-setup-python-v5-2-0-lion-blue-plum
      port: exec
    dst:
      node: run-v1-zebra-banana-pineapple
      port: exec
  - src:
      node: run-v1-zebra-banana-pineapple
      port: exec-success
    dst:
      node: run-v1-peach-dolphin-pineapple
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 100
      y: 100
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 450
      y: 100
    inputs:
      fetch-depth: '0'
    settings:
      folded: false
  - id: gh-actions-setup-python-v5-2-0-lion-blue-plum
    type: github.com/actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
    position:
      x: 980
      y: 120
    inputs:
      python-version: 3.11.9
    settings:
      folded: false
  - id: run-v1-peach-dolphin-pineapple
    type: run@v1
    position:
      x: 1760
      y: 220
    inputs:
      script: uv pip install -r requirements.txt
    settings:
      folded: false
  - id: run-v1-orange-panda-gray
    type: run@v1
    position:
      x: 2160
      y: 440
    inputs:
      script: pytest --cov --junitxml=junit.xml
    settings:
      folded: false
  - id: gh-codecov-codecov-action-v4-5-0-pomegranate-blueberry-red
    type: github.com/codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
    position:
      x: 2590
      y: -200
    inputs:
      name: Upload results to Codecov
      token: ${{ secrets.CODECOV_TOKEN }}
    settings:
      folded: false
  - id: run-v1-zebra-banana-pineapple
    type: run@v1
    position:
      x: 1410
      y: 20
    inputs:
      script: uv pip install --upgrade pip
    settings:
      folded: false
registries:
  - github.com/actions/setup-python@v5.2.0
  - github.com/codecov/codecov-action@v4.5.0
description: ''
