model_list:
- model_name: mistral-nemo
  litellm_params:
    model: ollama/mistral-nemo:latest
    api_base: http://127.0.0.1:11434
- model_name: gemini-flash
  litellm_params:
    model: gemini/gemini-1.5-flash
    api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL

litellm_settings:
  set_verbose: True
  drop_params: True
  success_callback: ["traceloop"]
  num_retries: 5
  request_timeout: 6000
  fallbacks: [{"gemini-flash": ["mistral-nemo"]}]
  context_window_fallbacks: [{"gemini-flash": ["mistral-nemo"]}]

router_settings:
  routing_strategy: usage-based-routing-v2
  num_retries: 2
  timeout: 30

# environment_variables:
#   TRACELOOP_API_KEY: os.environ/TRACELOOP_API_KEY
