[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = setuptools.build_meta

[project]
name = "mlx_api"
version = "0.0.0"
description = "A RAG chat UI powered by open source models. Optimized for M Series Unified Architecture environments."
readme = "README.md"
keywords = "apple", "silicon" "retrieval", "augmented", "generation", "chat", "user", "interface", "artificial", "intelligence", "chatbot"
authors = [
	{ name = "Adam kabak", email = "adamkabak@gmail.com"},{ name = "Antonio Reid", "read.musik@gmail.com" }
]

license = { text = "MIT License" }

classifiers = [
	"Development Status :: 1 - Alpha",
	"License :: MIT License",
	"Operating System :: MacOS",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.11",
	"Topic :: Scientific/Engineering :: Artificial Intelligence",
]

requires-python = ">= 3.10"

dependencies = [
	aiosignal==1.3.1
	aiofixles==23.2.1
	aiohappyeyeballs==2.4.0
	aiohttp==3.10.5
	aiosignal==1.3.1
	annotated-types==0.7.0
	anyio==4.4.0
	asgiref==3.8.1
	attrs==24.2.0
	backoff==2.2.1
	backports.tarfile==1.2.0
	bandit==1.7.9
	bcrypt==4.2.0
	build==1.2.1
	cachetools==5.5.0
	certifi==2024.7.4
	cfgv==3.4.0
	chardet==5.2.0
	charset-normalizer==3.3.2
	chroma-hnswlib==0.7.6
	chromadb==0.5.5
	click==8.1.7
	colorama==0.4.6
	coloredlogs==15.0.1
	contourpy==1.3.0
	cycler==0.12.1
	dataclasses-json==0.6.7
	Deprecated==1.2.14
	distlib==0.3.8
	docutils==0.21.2
	docx2txt==0.8
	einops==0.8.0
	fastapi==0.112.2
	ffmpy==0.4.0
	filelock==3.15.4
	flatbuffers==24.3.25
	fonttools==4.53.1
	frozenlist==1.4.1
	fsspec==2024.6.1
	google-auth==2.34.0
	googleapis-common-protos==1.65.0
	gradio==4.42.0
	gradio_client==1.3.0
	grpcio==1.66.1
	h11==0.14.0
	httpcore==1.0.5
	httptools==0.6.1
	httpx==0.27.2
	huggingface-hub==0.24.6
	humanfriendly==10.0
	identify==2.6.0
	idna==3.8
	importlib_metadata==8.4.0
	importlib_resources==6.4.4
	jaraco.classes==3.4.0
	jaraco.context==6.0.1
	jaraco.functools==4.0.2
	Jinja2==3.1.4
	joblib==1.4.2
	jsonpatch==1.33
	jsonpointer==3.0.0
	keyring==25.3.0
	kiwisolver==1.4.5
	kubernetes==30.1.0
	langchain==0.2.15
	langchain-community==0.2.14
	langchain-core==0.2.36
	langchain-text-splitters==0.2.2
	langsmith==0.1.107
	markdown-it-py==3.0.0
	MarkupSafe==2.1.5
	marshmallow==3.22.0
	matplotlib==3.9.2
	mdurl==0.1.2
	mlx==0.17.1
	mlx-lm==0.17.1
	mmh3==4.1.0
	monotonic==1.6
	more-itertools==10.4.0
	mpmath==1.3.0
	multidict==6.0.5
	mypy-extensions==1.0.0
	networkx==3.3
	nh3==0.2.18
	nodeenv==1.9.1
	numpy==1.26.4
	oauthlib==3.2.2
	onnxruntime==1.19.0
	opentelemetry-api==1.27.0
	opentelemetry-exporter-otlp-proto-common==1.27.0
	opentelemetry-exporter-otlp-proto-grpc==1.27.0
	opentelemetry-instrumentation==0.48b0
	opentelemetry-instrumentation-asgi==0.48b0
	opentelemetry-instrumentation-fastapi==0.48b0
	opentelemetry-proto==1.27.0
	opentelemetry-sdk==1.27.0
	opentelemetry-semantic-conventions==0.48b0
	opentelemetry-util-http==0.48b0
	orjson==3.10.7
	overrides==7.7.0
	packaging==24.1
	pandas==2.2.2
	pbr==6.1.0
	pillow==10.4.0
	pkginfo==1.10.0
	platformdirs==4.2.2
	pluggy==1.5.0
	posthog==3.6.0
	pre-commit==3.8.0
	protobuf==4.25.4
	pyasn1==0.6.0
	pyasn1_modules==0.4.0
	pydantic==2.8.2
	pydantic_core==2.20.1
	pydub==0.25.1
	Pygments==2.18.0
	pyparsing==3.1.4
	pypdf==4.3.1
	PyPika==0.48.9
	pyproject-api==1.7.1
	pyproject_hooks==1.1.0
	python-dateutil==2.9.0.post0
	python-dotenv==1.0.1
	python-multipart==0.0.9
	pytz==2024.1
	PyYAML==6.0.2
	readme_renderer==44.0
	regex==2024.7.24
	requests==2.32.3
	requests-oauthlib==2.0.0
	requests-toolbelt==1.0.0
	rfc3986==2.0.0
	rich==13.8.0
	rsa==4.9
	ruff==0.6.3
	safetensors==0.4.4
	scikit-learn==1.5.1
	scipy==1.14.1
	semantic-version==2.10.0
	sentence-transformers==3.0.1
	sentencepiece==0.2.0
	shellingham==1.5.4
	six==1.16.0
	sniffio==1.3.1
	SQLAlchemy==2.0.32
	starlette==0.38.2
	stevedore==5.3.0
	sympy==1.13.2
	tenacity==8.5.0
	threadpoolctl==3.5.0
	tiktoken==0.7.0
	tokenizers==0.19.1
	tomlkit==0.12.0
	torch==2.4.0
	tox==4.18.0
	tqdm==4.66.5
	transformers==4.44.2
	twine==5.1.1
	typer==0.12.5
	typing-inspect==0.9.0
	typing_extensions==4.12.2
	tzdata==2024.1
	urllib3==2.2.2
	uvicorn==0.30.6
	uvloop==0.20.0
	virtualenv==20.26.3
	watchfiles==0.24.0
	websocket-client==1.8.0
	websockets==12.0
	wrapt==1.16.0
	yarl==1.9.4
	zipp==3.20.1
]

[tool.isort]
line_length = 88
profile = "black"

[tool.bandit]
target = ["mlx_api"]
tests = ["B201", "B301", "B318", "B314", "B303", "B413", "B412", "B201", "B410"]

[tool.autoflake]
check = true
imports = ["mlx_api"]

[tool.ruff]
target-version = "py38"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "yarn-error.log",
    "yarn.lock",
    "docs",
]

line-length = 88
indent-width = 4

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
pylint.max-args = 20

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402","F401"]

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 20

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.setuptools]
package-dir = {"mlx_apy" = "mlx_api"}
include-package-data = true
license-files = ["LICENSE"]
zip-safe = true

[tool.setuptools.packages.find]
include = ["mlx_api*"]
exclude = ["docs*", "tests*","third_party*","assets*", "chat_with_mlx/models/*"]

[project.scripts]

mxl-api = "mlx_apy.mlx_apy.main
aiofiles==23.2.1
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.4.0
asgiref==3.8.1
attrs==24.2.0
backoff==2.2.1
backports.tarfile==1.2.0
bandit==1.7.9
bcrypt==4.2.0
build==1.2.1
cachetools==5.5.0
certifi==2024.7.4
cfgv==3.4.0
chardet==5.2.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.6
chromadb==0.5.5
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.0
cycler==0.12.1
dataclasses-json==0.6.7
Deprecated==1.2.14
distlib==0.3.8
docutils==0.21.2
docx2txt==0.8
einops==0.8.0
fastapi==0.112.2
ffmpy==0.4.0
filelock==3.15.4
flatbuffers==24.3.25
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
google-auth==2.34.0
googleapis-common-protos==1.65.0
gradio==4.42.0
gradio_client==1.3.0
grpcio==1.66.1
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.2
huggingface-hub==0.24.6
humanfriendly==10.0
identify==2.6.0
idna==3.8
importlib_metadata==8.4.0
importlib_resources==6.4.4
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.0.2
Jinja2==3.1.4
joblib==1.4.2
jsonpatch==1.33
jsonpointer==3.0.0
keyring==25.3.0
kiwisolver==1.4.5
kubernetes==30.1.0
langchain==0.2.15
langchain-community==0.2.14
langchain-core==0.2.36
langchain-text-splitters==0.2.2
langsmith==0.1.107
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.22.0
matplotlib==3.9.2
mdurl==0.1.2
mlx==0.17.1
mlx-lm==0.17.1
mmh3==4.1.0
monotonic==1.6
more-itertools==10.4.0
mpmath==1.3.0
multidict==6.0.5
mypy-extensions==1.0.0
networkx==3.3
nh3==0.2.18
nodeenv==1.9.1
numpy==1.26.4
oauthlib==3.2.2
onnxruntime==1.19.0
opentelemetry-api==1.27.0
opentelemetry-exporter-otlp-proto-common==1.27.0
opentelemetry-exporter-otlp-proto-grpc==1.27.0
opentelemetry-instrumentation==0.48b0
opentelemetry-instrumentation-asgi==0.48b0
opentelemetry-instrumentation-fastapi==0.48b0
opentelemetry-proto==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
opentelemetry-util-http==0.48b0
orjson==3.10.7
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pbr==6.1.0
pillow==10.4.0
pkginfo==1.10.0
platformdirs==4.2.2
pluggy==1.5.0
posthog==3.6.0
pre-commit==3.8.0
protobuf==4.25.4
pyasn1==0.6.0
pyasn1_modules==0.4.0
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
Pygments==2.18.0
pyparsing==3.1.4
pypdf==4.3.1
PyPika==0.48.9
pyproject-api==1.7.1
pyproject_hooks==1.1.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.2
readme_renderer==44.0
regex==2024.7.24
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.8.0
rsa==4.9
ruff==0.6.3
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.1
semantic-version==2.10.0
sentence-transformers==3.0.1
sentencepiece==0.2.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
SQLAlchemy==2.0.32
starlette==0.38.2
stevedore==5.3.0
sympy==1.13.2
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.7.0
tokenizers==0.19.1
tomlkit==0.12.0
torch==2.4.0
tox==4.18.0
tqdm==4.66.5
transformers==4.44.2
twine==5.1.1
typer==0.12.5
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
uvloop==0.20.0
virtualenv==20.26.3
watchfiles==0.24.0
websocket-client==1.8.0
websockets==12.0
wrapt==1.16.0
yarl==1.9.4
zipp==3.20.1
aiofiles==23.2.1
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.4.0
asgiref==3.8.1
attrs==24.2.0
backoff==2.2.1
backports.tarfile==1.2.0
bandit==1.7.9
bcrypt==4.2.0
build==1.2.1
cachetools==5.5.0
certifi==2024.7.4
cfgv==3.4.0
chardet==5.2.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.6
chromadb==0.5.5
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.0
cycler==0.12.1
dataclasses-json==0.6.7
Deprecated==1.2.14
distlib==0.3.8
docutils==0.21.2
docx2txt==0.8
einops==0.8.0
fastapi==0.112.2
ffmpy==0.4.0
filelock==3.15.4
flatbuffers==24.3.25
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
google-auth==2.34.0
googleapis-common-protos==1.65.0
gradio==4.42.0
gradio_client==1.3.0
grpcio==1.66.1
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.2
huggingface-hub==0.24.6
humanfriendly==10.0
identify==2.6.0
idna==3.8
importlib_metadata==8.4.0
importlib_resources==6.4.4
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.0.2
Jinja2==3.1.4
joblib==1.4.2
jsonpatch==1.33
jsonpointer==3.0.0
keyring==25.3.0
kiwisolver==1.4.5
kubernetes==30.1.0
langchain==0.2.15
langchain-community==0.2.14
langchain-core==0.2.36
langchain-text-splitters==0.2.2
langsmith==0.1.107
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.22.0
matplotlib==3.9.2
mdurl==0.1.2
mlx==0.17.1
mlx-lm==0.17.1
mmh3==4.1.0
monotonic==1.6
more-itertools==10.4.0
mpmath==1.3.0
multidict==6.0.5
mypy-extensions==1.0.0
networkx==3.3
nh3==0.2.18
nodeenv==1.9.1
numpy==1.26.4
oauthlib==3.2.2
onnxruntime==1.19.0
opentelemetry-api==1.27.0
opentelemetry-exporter-otlp-proto-common==1.27.0
opentelemetry-exporter-otlp-proto-grpc==1.27.0
opentelemetry-instrumentation==0.48b0
opentelemetry-instrumentation-asgi==0.48b0
opentelemetry-instrumentation-fastapi==0.48b0
opentelemetry-proto==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
opentelemetry-util-http==0.48b0
orjson==3.10.7
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pbr==6.1.0
pillow==10.4.0
pkginfo==1.10.0
platformdirs==4.2.2
pluggy==1.5.0
posthog==3.6.0
pre-commit==3.8.0
protobuf==4.25.4
pyasn1==0.6.0
pyasn1_modules==0.4.0
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
Pygments==2.18.0
pyparsing==3.1.4
pypdf==4.3.1
PyPika==0.48.9
pyproject-api==1.7.1
pyproject_hooks==1.1.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.2
readme_renderer==44.0
regex==2024.7.24
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.8.0
rsa==4.9
ruff==0.6.3
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.1
semantic-version==2.10.0
sentence-transformers==3.0.1
sentencepiece==0.2.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
SQLAlchemy==2.0.32
starlette==0.38.2
stevedore==5.3.0
sympy==1.13.2
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.7.0
tokenizers==0.19.1
tomlkit==0.12.0
torch==2.4.0
tox==4.18.0
tqdm==4.66.5
transformers==4.44.2
twine==5.1.1
typer==0.12.5
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
uvloop==0.20.0
virtualenv==20.26.3
watchfiles==0.24.0
websocket-client==1.8.0
websockets==12.0
wrapt==1.16.0
yarl==1.9.4
zipp==3.20.1